version: "3"

services:
  backend:
    build: .
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - NAME="Gino"
    logging:
      driver: "loki"
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  grafana:
    image: "grafana/grafana:8.4.2"
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  loki:
    image: "grafana/loki:2.4.2"
    ports:
      - "3100:3100"
